name: Docker Build/Publish Image
on:
  push:
    branches:
    - main
  schedule:
  - cron:  '15 6 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-branch.yaml@main
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm64/v8
